### ISSUE TITLE
A issue on Usage

### ISSUE THREAD

**Issue by ZJG0** [carter-yagemann/python-fuzzy-extractor#5]
Hello，In the example,you only use the string as the input. I want to know whether the`python-fuzzy-extractor` can use matrix or array as the input. If can,it how to compute the similarity

**Comment by carter-yagemann** [comment]
Sorry for not seeing this issue sooner. For future reference, this library is only designed to work on byte strings. For other data types, it may be possible to use [locality-sensitive hashing](https://en.wikipedia.org/wiki/Locality-sensitive_hashing) to project your data into a hash string that can then be given to the fuzzy extractor. Unfortunately, I have not tested any Python LSH implementations.

**Comment by GeorgiyNaumenko** [comment]
> Hello，In the example,you only use the string as the input. I want to know whether the`python-fuzzy-extractor` can use matrix or array as the input. If can,it how to compute the similarity

If you have some array, you can calculate a new one using some activation function (like sigmoid), then you have an array which values are between 0 and 1, multiple it by 255 and get an array which values are between 0 and 255. Round it to the nearest integer and use np.uint8 dtype - this array you can use as input to FE. The length of your 1-D array must be equal to bytes you use (first FE parameter), so if you have longer array or multiple arrays, you can select stable features or something like that.
