### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by LeviathanGod** [carter-yagemann/python-fuzzy-extractor#6]
I can't build it
![image](https://user-images.githubusercontent.com/106419343/172819732-1978122d-9a92-4523-b88a-e5dedb5eef3e.png)

**Comment by carter-yagemann** [comment]
Hi @LeviathanGod, I'm not encountering this issue on my end. Have you tried installing the missing openssl developer headers? For Debian, it's `sudo apt install libssl-dev`.

**Comment by moerv9** [comment]
I am on Mac and have the current openssl library which would be the same as libssl according to stackoverflow but it didn't fix it...
