### ISSUE TITLE
Failed building wheel for fastpbkdf2

### ISSUE THREAD

**Issue by moerv9** [carter-yagemann/python-fuzzy-extractor#7]
Hi Carter,

Would love to try out your work, but when I try to install it with `pip install fuzzy-extractor`, I get an error (see txt file)...

Do you know what to do? I couldn't figure it out with StackOverflow....
Cheers
Marvin

[install_fuzzy_log.txt](https://github.com/carter-yagemann/python-fuzzy-extractor/files/10716375/install_fuzzy_log.txt)

**Comment by carter-yagemann** [comment]
Hi @moerv9,

Your issue might be related to #6
