### ISSUE TITLE
About the theoretical plan of the project

### ISSUE THREAD

**Issue by 950706** [carter-yagemann/python-fuzzy-extractor#8]
Sorry to bother you, I am learning fuzzy extractor. I have a question and I would like to ask for your answer. I am a complete novice and need to learn the theory and practice accordingly. So I wanted to ask about the theoretical scheme of the fuzzy extractor you implemented in this project is the paper Canetti, Ran, et al. "Reusable fuzzy extractors for low-entropy distributions." Annual International Conference on the Theory and Applications of Cryptographic Techniques. Springer , Berlin, Heidelberg, 2016? Looking forward to getting your answer, thank you very much!

**Comment by carter-yagemann** [comment]
If I understand your question correctly, yes, the implementation in this project is based on the Canetti, et al. paper. We use the same primitives as that paper (e.g., digital lockers, helper strings) and aim to be secure under the proof they provide. However, this is best effort "research quality code" so we make no formal guarantee that we have correctly implemented the paper's design. If you uncover any flaws in the implementation, please let us know.

Hopefully that answers your question. If not, feel free to reopen this issue.

**Comment by 950706** [comment]
Thank you very much for answering my questions despite your busy schedule. This has brought great help and encouragement to my study.


小白
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "carter-yagemann/python-fuzzy-extractor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月29日(星期三) 凌晨4:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [carter-yagemann/python-fuzzy-extractor] About the theoretical plan of the project (Issue #8)





 
If I understand your question correctly, yes, the implementation in this project is based on the Canetti, et al. paper. We use the same primitives as that paper (e.g., digital lockers, helper strings) and aim to be secure under the proof they provide. However, this is best effort "research quality code" so we make no formal guarantee that we have correctly implemented the paper's design. If you uncover any flaws in the implementation, please let us know.
 
Hopefully that answers your question. If not, feel free to reopen this issue.
